# Form implementation generated from reading ui file 'd:\Storage\Desktop\OneDrive_2025-02-28\NEA Sigma\Register.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 362)
        self.Logo = QtWidgets.QLabel(parent=Form)
        self.Logo.setGeometry(QtCore.QRect(50, 10, 301, 101))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("Assets/Logos/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.LUsername = QtWidgets.QLabel(parent=Form)
        self.LUsername.setGeometry(QtCore.QRect(30, 149, 81, 31))
        self.LUsername.setObjectName("LUsername")
        self.LPassword = QtWidgets.QLabel(parent=Form)
        self.LPassword.setGeometry(QtCore.QRect(30, 200, 81, 31))
        self.LPassword.setObjectName("LPassword")
        self.PBRegister = QtWidgets.QPushButton(parent=Form)
        self.PBRegister.setGeometry(QtCore.QRect(160, 320, 81, 31))
        self.PBRegister.setObjectName("PBRegister")
        self.LPassword_2 = QtWidgets.QLabel(parent=Form)
        self.LPassword_2.setGeometry(QtCore.QRect(30, 260, 81, 31))
        self.LPassword_2.setObjectName("LPassword_2")
        self.LPassword_3 = QtWidgets.QLabel(parent=Form)
        self.LPassword_3.setGeometry(QtCore.QRect(30, 240, 81, 41))
        self.LPassword_3.setObjectName("LPassword_3")
        self.LEUsername = QtWidgets.QLineEdit(parent=Form)
        self.LEUsername.setGeometry(QtCore.QRect(112, 149, 261, 31))
        self.LEUsername.setObjectName("LEUsername")
        self.LEPassword = QtWidgets.QLineEdit(parent=Form)
        self.LEPassword.setGeometry(QtCore.QRect(112, 199, 261, 31))
        self.LEPassword.setObjectName("LEPassword")
        self.LEPasswordConfirm = QtWidgets.QLineEdit(parent=Form)
        self.LEPasswordConfirm.setGeometry(QtCore.QRect(112, 250, 261, 31))
        self.LEPasswordConfirm.setObjectName("LEPasswordConfirm")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.LEUsername, self.LEPassword)
        Form.setTabOrder(self.LEPassword, self.LEPasswordConfirm)
        Form.setTabOrder(self.LEPasswordConfirm, self.PBRegister)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LUsername.setText(_translate("Form", "Username:"))
        self.LPassword.setText(_translate("Form", "Password:"))
        self.PBRegister.setText(_translate("Form", "Register"))
        self.LPassword_2.setText(_translate("Form", "Password:"))
        self.LPassword_3.setText(_translate("Form", "Confirm"))
