# Form implementation generated from reading ui file 'd:\Storage\Desktop\Sigma-Maths-Rewrite\Assets\UI Files\MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 755)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(30, 30, 731, 251))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("d:\\Storage\\Desktop\\Sigma-Maths-Rewrite\\Assets\\UI Files\\logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.PBPractice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBPractice.setGeometry(QtCore.QRect(30, 320, 341, 121))
        self.PBPractice.setObjectName("PBPractice")
        self.PBViewMarks = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBViewMarks.setGeometry(QtCore.QRect(410, 320, 351, 121))
        self.PBViewMarks.setObjectName("PBViewMarks")
        self.PBExamMode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBExamMode.setGeometry(QtCore.QRect(410, 460, 351, 121))
        self.PBExamMode.setObjectName("PBExamMode")
        self.PBStatistics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBStatistics.setGeometry(QtCore.QRect(30, 460, 341, 121))
        self.PBStatistics.setObjectName("PBStatistics")
        self.PBSettings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBSettings.setGeometry(QtCore.QRect(30, 600, 731, 51))
        self.PBSettings.setObjectName("PBSettings")
        self.PBQuit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBQuit.setGeometry(QtCore.QRect(30, 670, 731, 51))
        self.PBQuit.setObjectName("PBQuit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PBPractice.setText(_translate("MainWindow", "Practice"))
        self.PBViewMarks.setText(_translate("MainWindow", "View Marks"))
        self.PBExamMode.setText(_translate("MainWindow", "Exam Mode"))
        self.PBStatistics.setText(_translate("MainWindow", "Statistics"))
        self.PBSettings.setText(_translate("MainWindow", "Settings"))
        self.PBQuit.setText(_translate("MainWindow", "Quit"))
