# Form implementation generated from reading ui file 'd:\Storage\Desktop\OneDrive_2025-02-28\NEA Sigma\Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(401, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Logos/logosmall.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Login.setWindowIcon(icon)
        self.Logo = QtWidgets.QLabel(parent=Login)
        self.Logo.setGeometry(QtCore.QRect(50, 10, 301, 101))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("Assets/Logos/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.LUsername = QtWidgets.QLabel(parent=Login)
        self.LUsername.setGeometry(QtCore.QRect(30, 149, 81, 31))
        self.LUsername.setObjectName("LUsername")
        self.LPassword = QtWidgets.QLabel(parent=Login)
        self.LPassword.setGeometry(QtCore.QRect(30, 200, 81, 31))
        self.LPassword.setObjectName("LPassword")
        self.PBRegister = QtWidgets.QPushButton(parent=Login)
        self.PBRegister.setGeometry(QtCore.QRect(50, 252, 111, 31))
        self.PBRegister.setObjectName("PBRegister")
        self.PBLogin = QtWidgets.QPushButton(parent=Login)
        self.PBLogin.setGeometry(QtCore.QRect(240, 252, 111, 31))
        self.PBLogin.setObjectName("PBLogin")
        self.LEPassword = QtWidgets.QLineEdit(parent=Login)
        self.LEPassword.setGeometry(QtCore.QRect(110, 200, 261, 31))
        self.LEPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LEPassword.setObjectName("LEPassword")
        self.LEUsername = QtWidgets.QLineEdit(parent=Login)
        self.LEUsername.setGeometry(QtCore.QRect(110, 150, 261, 31))
        self.LEUsername.setObjectName("LEUsername")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.LEUsername, self.LEPassword)
        Login.setTabOrder(self.LEPassword, self.PBRegister)
        Login.setTabOrder(self.PBRegister, self.PBLogin)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.LUsername.setText(_translate("Login", "Username:"))
        self.LPassword.setText(_translate("Login", "Password:"))
        self.PBRegister.setText(_translate("Login", "Register"))
        self.PBLogin.setText(_translate("Login", "Login"))
